"""
security.py — Security Intelligence API Routes
------------------------------------------------
Exposes the five security service functions as REST endpoints.

Endpoints:
  GET /security/audit-logs           — recent audit trail entries
  GET /security/classifications      — sample dataset classification examples
  GET /security/threat-alerts        — simulated threat detections
  GET /security/system-status        — secure-processing indicator badges
  GET /security/collaboration-status — inter-agency collaboration metadata
"""

from fastapi import APIRouter, Query
from backend.app.services.security import (
    get_audit_logs,
    classify_dataset,
    generate_threat_alerts,
    get_system_status,
    get_collaboration_status,
    log_event,
)

router = APIRouter(prefix="/security", tags=["Security & Compliance"])


@router.get("/audit-logs", summary="Recent platform audit trail")
def audit_logs(limit: int = Query(default=50, ge=1, le=200,
                                  description="Number of log entries to return (1–200)")):
    """
    Returns the most recent audit events logged by the platform.
    Each entry includes timestamp, action, module, status, and detail.
    Logs are written whenever uploads, forecasts, or API calls occur.
    """
    # Log this read itself so the audit trail is self-referential
    log_event("audit_log_read", "security", "success", f"limit={limit}")
    logs = get_audit_logs(limit=limit)
    return {
        "total_returned": len(logs),
        "limit":          limit,
        "logs":           logs,
    }


@router.get("/classifications", summary="Dataset classification examples")
def classifications():
    """
    Runs classify_dataset() against a set of representative filenames
    to demonstrate the four classification tiers in action.

    In production this would classify real uploaded files.
    For the PoC it returns a fixed sample set for demo purposes.
    """
    log_event("classifications_read", "security", "success")

    # Representative filenames covering all four classification levels
    sample_files = [
        "cargo_data_jun2024.csv",
        "vessel_movements_may.csv",
        "port_congestion_history.csv",
        "trade_customs_report.csv",
        "export_licence_dgft.csv",
        "public_port_statistics.csv",
        "restricted_sensitive_manifest.csv",
    ]

    return {
        "classification_scheme": "Maritime Data Sensitivity Framework v1.0",
        "levels": ["Public", "Internal", "Restricted", "Confidential"],
        "classifications": [
            {"filename": f, **classify_dataset(f)}
            for f in sample_files
        ],
    }


@router.get("/threat-alerts", summary="Simulated cybersecurity threat detections")
def threat_alerts(count: int = Query(default=5, ge=1, le=7,
                                     description="Number of alerts to return (1–7)")):
    """
    Returns simulated threat alerts generated by the security engine.
    Each alert includes severity, MITRE ATT&CK reference, source module,
    and a human-readable description for the security operations panel.
    """
    log_event("threat_alerts_read", "security", "success", f"count={count}")
    alerts = generate_threat_alerts(count=count)

    # Summary counts by severity for dashboard KPI cards
    summary = {s: sum(1 for a in alerts if a["severity"] == s)
               for s in ("critical", "high", "medium", "low")}

    return {
        "total_alerts": len(alerts),
        "summary":      summary,
        "alerts":       alerts,
    }


@router.get("/system-status", summary="Secure processing and compliance indicators")
def system_status():
    """
    Returns the platform's security posture indicators.
    Includes encryption status, compliance flags, and processing
    environment indicators suitable for a government/enterprise demo.
    """
    log_event("system_status_read", "security", "success")
    return get_system_status()


@router.get("/collaboration-status", summary="Inter-agency secure collaboration status")
def collaboration_status():
    """
    Returns the status of the inter-agency secure data-sharing fabric.
    Shows which government agencies are connected, pending, or offline,
    along with their data-sharing agreements and clearance levels.
    """
    log_event("collaboration_read", "security", "success")
    return get_collaboration_status()
